TOP     = ticprec_top
SOURCES = rtl/ticprec_top.v ../../gpsdo/rtl/tic.v ../../gpsdo/rtl/tdc.v \
          ../../gpsdo/rtl/tdc_chain.v ../../gpsdo/rtl/tdc_core.v \
          ../../gpsdo/rtl/ring_osc.v ../../gpsdo/rtl/uart_tx.v

include ../../mk/gowin.mk
