TOP     = radio433_top
SOURCES = rtl/radio433_top.v rtl/ook_rx.v rtl/spi_cfg.v rtl/glitch_filt.v \
          rtl/pwm_slice.v rtl/sync_frame.v rtl/nrz_sample.v rtl/uart_rx.v \
          rtl/nexus_decode.v rtl/nexus_encode.v rtl/manch_decode.v \
          ../../gpsdo/rtl/uart_tx.v ../../gpsdo/rtl/pps_capture.v \
          ../../gpsdo/rtl/rf_stamp.v ../../gpsdo/rtl/tdc.v \
          ../../gpsdo/rtl/tdc_chain.v ../../gpsdo/rtl/tdc_core.v
CST_EXTRA = radio433.cst

include ../../mk/gowin.mk
