TOP     = xocal_top
SOURCES = rtl/xocal_top.v rtl/xo_meter.v ../radio433/rtl/spi_cfg.v \
          ../../gpsdo/rtl/uart_tx.v ../../gpsdo/rtl/pps_capture.v
CST_EXTRA = ../radio433/radio433.cst

include ../../mk/gowin.mk
